version: '3.8'

services:
  customer-db:
    image: postgres:15.2
    container_name: customer_db
    restart: always
    volumes:
      - database-data-customer:/var/lib/postgresql/data/
      - ./customer/db/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
    environment:
      - POSTGRES_DB=customer_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - aplazo-net
  customer-app:
    image: 'customer-app:latest'
    build:
      context: ./customer
      dockerfile: Dockerfile
    container_name: customer-app
    depends_on:
      - customer-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://customer-db:5432/customer_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "8080:8080"
    networks:
      - aplazo-net

  credit-line-db:
    image: postgres:15.2
    container_name: credit_line_db
    restart: always
    volumes:
      - database-data-credit-line:/var/lib/postgresql/data/
      - ./credit-line/db/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
    environment:
      - POSTGRES_DB=credit_line_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    networks:
      - aplazo-net
  credit-line-app:
    image: 'credit-line-app:latest'
    build:
      context: ./credit-line
      dockerfile: Dockerfile
    container_name: credit-line-app
    depends_on:
      - credit-line-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://credit-line-db:5432/credit_line_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "8081:8081"
    networks:
      - aplazo-net

  scheme-db:
    image: postgres:15.2
    container_name: scheme_db
    restart: always
    volumes:
      - database-data-scheme:/var/lib/postgresql/data/
      - ./scheme/db/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
    environment:
      - POSTGRES_DB=scheme_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"
    networks:
      - aplazo-net
  scheme-app:
    image: 'scheme-app:latest'
    build:
      context: ./scheme
      dockerfile: Dockerfile
    container_name: scheme-app
    depends_on:
      - scheme-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://scheme-db:5432/scheme_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "8082:8082"
    networks:
      - aplazo-net

  loan-db:
    image: postgres:15.2
    container_name: loan_db
    restart: always
    volumes:
      - database-data-loan:/var/lib/postgresql/data/
      - ./loan/db/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
    environment:
      - POSTGRES_DB=loan_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5435:5432"
    networks:
      - aplazo-net
  loan-app:
    image: 'loan-app:latest'
    build:
      context: ./loan
      dockerfile: Dockerfile
    container_name: loan-app
    depends_on:
      - loan-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://loan-db:5432/loan_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "8083:8083"
    networks:
      - aplazo-net
volumes:
  database-data-customer: {}
  database-data-credit-line: {}
  database-data-scheme: {}
  database-data-loan: {}
networks:
  aplazo-net:
